export enum songTypes {
	SONGS_REQUESTED = 'SONGS_REQUESTED',
	GET_SONGS_SUCCESS = 'GET_SONGS_SUCCESS',
	GET_SONGS_FAILURE = 'GET_SONGS_FAILURE',

	SONG_STACK_PUSH = 'SONG_STACK_PUSH',
	SONG_STACK_PUSHED = 'SONG_STACK_PUSHED',
	SONG_STACK_POP = 'SONG_STACK_POP',
	SONG_STACK_POPPED = 'SONG_STACK_POPPED',

	HISTORY_STACK_PUSH = 'HISTORY_STACK_PUSH',
	HISTORY_STACK_PUSHED = 'HISTORY_STACK_PUSHED',
	HISTORY_STACK_POP = 'HISTORY_STACK_POP',
	HISTORY_STACK_POPPED = 'HISTORY_STACK_POPPED',

}